// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyvFSPggb0UwokU3UEPkpNsLcmFN24ubk',
    appId: '1:1066736444625:web:a17d52081d1daf379451f0',
    messagingSenderId: '1066736444625',
    projectId: 'fruit-hub-95853',
    authDomain: 'fruit-hub-95853.firebaseapp.com',
    storageBucket: 'fruit-hub-95853.firebasestorage.app',
    measurementId: 'G-2Q3VZ287XN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt8XUyXyuV7Pi6zsWu4kEQss-xPoqyRCU',
    appId: '1:1066736444625:android:c05465174ecfa2a79451f0',
    messagingSenderId: '1066736444625',
    projectId: 'fruit-hub-95853',
    storageBucket: 'fruit-hub-95853.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwrxxRtjly5RMU_UD9pmva1qByKAs8OJ0',
    appId: '1:1066736444625:ios:5f35f966b2774bff9451f0',
    messagingSenderId: '1066736444625',
    projectId: 'fruit-hub-95853',
    storageBucket: 'fruit-hub-95853.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwrxxRtjly5RMU_UD9pmva1qByKAs8OJ0',
    appId: '1:1066736444625:ios:5f35f966b2774bff9451f0',
    messagingSenderId: '1066736444625',
    projectId: 'fruit-hub-95853',
    storageBucket: 'fruit-hub-95853.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyvFSPggb0UwokU3UEPkpNsLcmFN24ubk',
    appId: '1:1066736444625:web:cc02862771a871639451f0',
    messagingSenderId: '1066736444625',
    projectId: 'fruit-hub-95853',
    authDomain: 'fruit-hub-95853.firebaseapp.com',
    storageBucket: 'fruit-hub-95853.firebasestorage.app',
    measurementId: 'G-RDBXP1XL76',
  );
}
